### ISSUE TITLE
NullReferenceException when trying to retrieve players in multiplayer

### ISSUE THREAD

**Issue by mflink3012** [mflink3012/spaceengineers-mod-teleportingsensors#6]
> Exception occurred: System.NullReferenceException: Object reference not set to an instance of an object.
>    at SpaceEngineers.Mod.TeleportingSensor.LogicComponent.<>c__DisplayClass12_0.<UpdateBeforeSimulation100>b__0(IMyPlayer p)
>    at Sandbox.Game.Multiplayer.MyPlayerCollection.VRage.Game.ModAPI.IMyPlayerCollection.GetPlayers(List'1 players, Func'2 collect)
>    at SpaceEngineers.Mod.TeleportingSensor.LogicComponent.UpdateBeforeSimulation100()
>    at VRage.Game.Components.MyGameLogicComponent.VRage.Game.Entity.EntityComponents.Interfaces.IMyGameLogicComponent.UpdateBeforeSimulation100(Boolean entityUpdate)
>    at Sandbox.Game.Entities.Cube.MyFunctionalBlock.UpdateBeforeSimulation100()
>    at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.UpdateBeforeSimulation100()
>    at Sandbox.Game.Entities.MyParallelEntityUpdateOrchestrator.DispatchBeforeSimulation()
>    at Sandbox.Game.Entities.MyEntities.UpdateBeforeSimulation()
>    at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
>    at Sandbox.Game.World.MySession.UpdateComponents()
>    at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
>    at Sandbox.MySandboxGame.Update()
>    at Sandbox.Engine.Platform.Game.UpdateInternal()
>    at Sandbox.Engine.Platform.Game.RunSingleFrame()
>    at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
>    at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
>    at Sandbox.Engine.Platform.Game.RunLoop()
>    at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
>    at SpaceEngineers.MyProgram.Main(String[] args)

**Comment by mflink3012** [comment]
Got that issue entering a teleporter while another player was joining in multiplayer (Friends).
